name: Build host tools

on:
  pull_request:
    paths:
      - 'include/**'
      - 'tools/**'
      - '.github/workflows/tools.yml'
  push:
    paths:
      - 'include/**'
      - 'tools/**'
      - '.github/workflows/tools.yml'
    branches:
      - nss-edma-rework

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tools:
    name: Build host tools for linux and macos based systems
    uses: openwrt/actions-shared-workflows/.github/workflows/tools.yml@main
